name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Exponemos los secrets como env (si no existen, quedan vacíos)
    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          target: default
          arch: x86_64
          build-tools: "34.0.0"

      # ---------- Build DEBUG ----------
      - name: Build Debug
        run: ./gradlew clean :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      # ---------- (Opcional) Build RELEASE firmado ----------
      # Solo corre si el secreto del keystore existe
      - name: Prepare keystore
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > signing.jks
          echo "STORE_FILE=$(pwd)/signing.jks" >> $GITHUB_ENV
          echo "STORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> $GITHUB_ENV
          echo "KEY_ALIAS=$ANDROID_KEY_ALIAS" >> $GITHUB_ENV
          echo "KEY_PASSWORD=$ANDROID_KEY_PASSWORD" >> $GITHUB_ENV

      - name: Build Release
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        run: ./gradlew :app:assembleRelease

      - name: Upload Release APK
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
